version: "3.1"
services:

  web:
    image: wordpress:5.6.0-php7.4-apache
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    env_file:
      - ./secret/dev.env
    ports:
      - "80:80"
      - "443:443"

  db:
    image: mariadb
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - ./secret/dev.env
    ports:
      - "8890:3306"

networks:
  default:
    external:
      name: amp-wp
